Написал документацию полностью
modx-pro/Docs pull request #582
Opened 2023-01-22 21:01 UTC by ShevArtV

2023-01-22 21:25 UTC, webinmd commented on ru/01_Компоненты/71_AjaxFormItLogin/01_Общие_сведения/02_Системные настройки.md
> +| **ajaxformitlogin_metrics**          | Нет                                                         | Определяет будут ли отправляться цели в Яндекс.Метрику. При значении Да и НЕ указанном ID счётчи
Скорей всего имелось ввиду НЕТ , вместо НЕ

2023-01-22 21:27 UTC, webinmd commented on ru/01_Компоненты/71_AjaxFormItLogin/01_Общие_сведения/03_Скрипты_и_Стили.md
> +или `validationErrorMessage`, если иноне не задано в хуках; `data` - массив данных с сервера, при этом в `data.errors` - список ошибок валидации, `data.redirectUrl` - ссылка
опечатка в **иноне**

2023-01-22 21:29 UTC, webinmd commented on ru/01_Компоненты/71_AjaxFormItLogin/01_Общие_сведения/03_Скрипты_и_Стили.md
> +По умолчанию файлы обрабатывается один файл. Обработка производится тремя методами `onUploadProgress`, `onUploadFinished`, `onUploadError`. Каждый из
По умолчанию файлы обрабатывается один файл. - не очень понятно что имеется ввиду

2023-01-22 21:30 UTC, webinmd commented on ru/01_Компоненты/71_AjaxFormItLogin/01_Общие_сведения/03_Скрипты_и_Стили.md
> +При подключении своих скриптов укажите тегу script атрибут `type="modile"`.
`type="modile"`. -> `type="module"`.

2023-01-22 21:33 UTC, webinmd requested changes
Необходимо исправить пару опечаток

2023-01-23 09:40 UTC, Ibochkarev approved these changes

2023-01-23 09:40 UTC, merged