Правка отступов контента под некоторые экраны
modx-pro/Docs pull request #723
Opened 2023-06-21 13:07 UTC by dimasites

Уменьшены отступы для нешироких desktop-ов,  увеличен контейнер с контентом для широких экранов.

## Описание улучшений

В последнее время люди жаловались что не влезают таблицы документации в экран, появляется горизонтальный скролл и не удобно читать.

Я увеличил контейнер с контентом на больших экранах, и уменьшил отступы для экранов ноутбуков. 

Проверял по этому URI: `/components/pdotools/snippets/pdoresources` — корректно без горизонтального скролла отображается теперь начиная с 1366px и шире. Мобильная версия не затронута изменениями.

Заодно переписал стили в LESS. Возможно вы захотите добавить LESS-компилятор в проект. Для сборки использую File Watcher PHPstorm, поэтому внешний сборщик мне не понадобился. Поправил ещё .editorconfig под для поддержки отступов в less-файлах в общем стиле.

## Актуальные проблемы

- https://t.me/ru_modx/625670
- https://t.me/c/1157463630/92451

2023-06-21 13:55 UTC, GulomovCreative reviewed
В проекте используется сборщик и less ты не предлагаешь установить less как зависимость, но предлагаешь хранить в исходниках less файлы, это несерьезно

2023-06-21 14:15 UTC, dimasites commented
> Возможно вы захотите добавить LESS-компилятор в проект.

Я же написал, что возможно вы захотите. Просто я не уверенно чувствую себя в настройке сборщиков т.к. лишь изредка ими пользуюсь, поэтому не добавил. Пожалуйста, помогите добавить сборщик, вот мои настройки [PhpStorm File Watcher](https://www.jetbrains.com/help/phpstorm/transpiling-sass-less-and-scss-to-css.html#less_sass_scss_compiling_to_css):

arguments (для **lessc**):
`--source-map=$FileNameWithoutExtension$.css.map
$FileName$
$FileNameWithoutExtension$.css`

output path to refresh:
$FileNameWithoutExtension$.css

P.S. Если это проблема - заберите собранный .css - файл и не будем усложнять. _Но на будущее компилятор подозреваю что все равно понадобится._

2023-06-21 16:27 UTC, GulomovCreative requested changes
Жду нескольких изменений:

1. Файлов less не должно быть, ровно также как .map
2. Неиспользуемых переменных не должно быть
3. Форматирование нужно вернуть как было

2023-06-21 16:49 UTC, dimasites commented
Готово. 

Глянь финальный diff: bз форматирования остались только начальные нули от моего линтера (не было единой стилистики, либо везде их писать, либо везде нет, см. вот [этот коммит](https://github.com/modx-pro/Docs/pull/723/commits/b1149bd4c15ce4899917f5cc09a75dd60130439d) и исправление опечаток (спасибо less-у)

Исходники и упоминания less пока выпилил.

2023-06-21 23:29 UTC, GulomovCreative commented
@dimasites Когда что-то переделываешь и нужен новый ревью, то ты можешь запросить через функционал github

2023-06-21 23:30 UTC, GulomovCreative requested changes
Ну, есть ряд проблем, глянь пожалуйста.

![изображение](https://github.com/modx-pro/Docs/assets/20814058/5bd814e3-27f7-4922-a8ae-d31bd347479f)

Мы с `!important` только усложним всё. Предлагаю переопределить компонент `VPDoc.vue` и уже там у тебя развяжутся руки

2023-06-22 11:10 UTC, dimasites commented
> Ну, есть ряд проблем, глянь пожалуйста.
> 
> ![изображение](https://user-images.githubusercontent.com/20814058/247786283-5bd814e3-27f7-4922-a8ae-d31bd347479f.png)

Проверял и до этого, и сейчас после синхронизации форка (там 2 коммита всего, без конфликтов) ещё раз проверил, записал видео с полным тестом, от запуска master-ветки и переключение на мою  https://yadi.sk/d/jC1igotRCOYuPg - эффекта как у тебя на скрине - повторить не получилось

> Мы с `!important` только усложним всё. Предлагаю переопределить компонент `VPDoc.vue` и уже там у тебя развяжутся руки

В theme такого [компонента нет](https://yadi.sk/i/MGeJkbluhiyhMA), как его на основе реализованных готовых создать и какой написать базовый код обертки, мне не очевидно, потому что (https://yadi.sk/i/h2k8d4iH4AhN1w), так что руки и правда «завязаны».

Если настаиваешь на расширении, я не против, но нужна помощь в подготовке базовой обертки, в которой понятно будет, где именно добавить/исправить CSS-код.

Как альтернативу предлагаю оставить текущую реализацию с триклятым !important, которая работает вроде бы корректно.

2023-06-22 12:37 UTC, GulomovCreative commented
> Проверял и до этого, и сейчас после синхронизации форка (там 2 коммита всего, без конфликтов) ещё раз проверил, записал видео с полным тестом, от запуска master-ветки и переключение на мою https://yadi.sk/d/jC1igotRCOYuPg - эффекта как у тебя на скрине - повторить не получилось

@dimasites Ну как это не получилось, если прямо на твоём же видео видно

![изображение](https://github.com/modx-pro/Docs/assets/20814058/4d8a021d-8d1a-4559-87a6-c4eb670cf4f3)

> Если настаиваешь на расширении, я не против, но нужна помощь в подготовке базовой обертки, в которой понятно будет, где именно добавить/исправить CSS-код.
> 
> Как альтернативу предлагаю оставить текущую реализацию с триклятым !important, которая работает вроде бы корректно.

Хорошо, давай с css разберешься, а там посмотрим

2023-06-22 13:14 UTC, dimasites commented
> Ну как это не получилось, если прямо на твоём же видео видно

Действительно) Я не любитель усложнять стили для отлова промежуточных разрешений, но согласен что правильнее, когда такой эффект вообще не повторить. Добавил правило для фикса.

2023-06-22 13:23 UTC, GulomovCreative requested changes
![изображение](https://github.com/modx-pro/Docs/assets/20814058/5bd814e3-27f7-4922-a8ae-d31bd347479f)

Справа на скрине видишь косяк? Пожалуйста, тестируй основательно прежде чем запрашивать request, спасибо!

2023-06-22 13:53 UTC, dimasites commented
> Справа на скрине видишь косяк? Пожалуйста, тестируй основательно прежде чем запрашивать request

Сорри, мой косяк, даже не первом скриншоте ты обвёл, а я не заметил(
Исправлено.

2023-06-22 14:51 UTC, GulomovCreative requested changes
![изображение](https://github.com/modx-pro/Docs/assets/20814058/3178d27e-fff7-4f36-8bdb-f8fca9f2aa7e)

![изображение](https://github.com/modx-pro/Docs/assets/20814058/c5bbf0e8-99d2-415b-ae15-60bdf65354c5)

Еще раз прощу, **протестировать** сначала основательно, а **потом** запрашивать request. Спасибо!

2023-06-22 16:29 UTC, dimasites commented
> Еще раз прощу, **протестировать** сначала основательно, а **потом** запрашивать request. Спасибо!

Для понимания, я проверяю: 375, 1024, 1280, 1366, 1440, 1600, 1920, 2560 ширину, а ради поддержания «идеальной резиновой верстки» нагромождать и делать неподдерживаемым (а без препроцессора это примерно так) код я в моём pull request не планировал. Вроде бы и не очень код разросся, ну и ок.

Раз без этого никак, то внёс правки. Конечно, стало ещё лучше. Спасибо за рекомендацию!

2023-06-23 12:48 UTC, GulomovCreative commented
> > Еще раз прощу, **протестировать** сначала основательно, а **потом** запрашивать request. Спасибо!
> 
> Для понимания, я проверяю: 375, 1024, 1280, 1366, 1440, 1600, 1920, 2560 ширину, а ради поддержания «идеальной резиновой верстки» нагромождать и делать неподдерживаемым (а без препроцессора это примерно так) код я в моём pull request не планировал. Вроде бы и не очень код разросся, ну и ок.

На всякий случай напомню, есть пользователи, которые могут просматривать сайт открыв браузер не на весь экран

2023-06-23 12:48 UTC, GulomovCreative commented
@dimasites PR можно протестировать?

2023-06-23 15:36 UTC, dimasites commented
> @dimasites PR можно протестировать?

Да. Сорри, забываю нажимать кнопочку re-request...

2023-06-24 13:15 UTC, GulomovCreative commented
@dimasites Протестировал. Идея хорошая, но реализация к сожалению не очень. Т.к. я не понял как при расширении контентной части ты аж задел блок оглавлений.

Всё вернул и в одну строчку расширил контентную часть страницы

2023-06-24 13:18 UTC, GulomovCreative approved these changes

2023-06-24 13:18 UTC, merged

2023-06-24 14:49 UTC, dimasites commented
> Т.к. я не понял как при расширении контентной части ты аж задел блок оглавлений.

@GulomovCreative я делал не только, как и писал в заголовке PR. В тексте сделал анонс только расширения контентной области, как основной правки среди других. Возможно стоило описать все, но я рассчитывал на то, что код не большой и понять что он делает можно прямо из doff-а. Сделал в общем я [новый PR, в котором предлагаю](https://github.com/modx-pro/Docs/pull/726) совмещенное решение